spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/final
    username: postgres
    password: root
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: public
